### ISSUE TITLE
Add API to attach multiple transports/parsers to a link

### ISSUE THREAD

**Issue by flixr** [paparazzi/pprzlink#11]
Currently one normally uses the `<transport>_check_and_parse` functions to - well - check if there are new input chars on the device and if yes parse them using the transport.

It would be good to have the possibility to easily attach multiple transports/parsers to a link and pass the incoming data to all of them.

See also #10

**Comment by podhrmic** [comment]
Is this still relevant? @flixr

**Comment by podhrmic** [comment]
@gautierhattenberger @flixr is there still interest to do this on the pprzlink side rather than on the higher level application side (such as paparazzi)?

**Comment by podhrmic** [comment]
Looks like this can be handled with user defined transports, see #70 for discussion.
