### ISSUE TITLE
Cleanup messages

### ISSUE THREAD

**Issue by fvantienen** [paparazzi/pprzlink#27]
We currently only have 6 messages free which is not that much anymore. I think it would be nice if we could cleanup some of the old/unused messages to avoid extending the ID at first.

Maybe later on we could extend the ID with a class like others also have, but for now I think it is best to just cleanup the not used messages.

**Comment by gautierhattenberger** [comment]
I totally agree to remove old unused messages.

I also want to write a roadmap for the conversion of the message format when I found the time.

**Comment by podhrmic** [comment]
So we are now officially out of free messages:( We can either clean up the unused ones, or extend the message ID to be 16bit and have practically unlimited number of messages. What do you think is better?

**Comment by podhrmic** [comment]
See #36 for some deleted messages

**Comment by gautierhattenberger** [comment]
See http://wiki.paparazziuav.org/wiki/Roadmap#Communication_Roadmap for the proposed message's roadmap

**Comment by podhrmic** [comment]
@gautierhattenberger I like it. In the meantime - I suggest if anyone needs a new message and there are no new slots, go `grep -r "MSG_NAME" sw/airborne/*` and if you get no hits you can remove that message.

**Comment by flixr** [comment]
I just want to point out that if a message is not used in the main code base, it doesn't necessarily mean that it is not used at all....
Some messages might be used by people who don't have their stuff in the main repo or are useful in general...

**Comment by podhrmic** [comment]
Reminder to myself: revisting lidar and px4flow messages, maybe than can be unified / extended with generic optic flow / lidar / sonar / agl messages

**Comment by podhrmic** [comment]
Hopefully closing with #41

**Comment by podhrmic** [comment]
Closing with #41
