### ISSUE TITLE
MISSION_GOTO_WP_LLA altitude unit mismatch

### ISSUE THREAD

**Issue by pgorczak** [paparazzi/pprzlink#63]
Just leaving this here because I don't know where the fix would go: The *[MISSION_GOTO_WP_LLA]* message is described as having a `wp_alt` field containing altitude in millimeters. When trying the mission module with *v5.12_stable*, the module actually interprets the value as meters.

[MISSION_GOTO_WP_LLA]: https://github.com/paparazzi/pprzlink/blob/master/message_definitions/v1.0/messages.xml#L2095

**Comment by gautierhattenberger** [comment]
It seems to be fine, the alt field should really be in mm. Can you be a bit more specific about your use-case ? Which firmware (rotorcraft or fixedwind) ? Which message did you sent and what was the result ?

**Comment by pgorczak** [comment]
Sure! I used fixedwing. You can reproduce it with the *easystar_ets* airframe and the *mission_fw* flight plan (sim target and Simulation). When sending

    datalink MISSION_GOTO_WP_LLA 4 3 434630000 12600000 90000 -1 0

and switching to Mission in GCS, the target altitude jumps to 90000 m.

**Comment by gautierhattenberger** [comment]
close with https://github.com/paparazzi/paparazzi/pull/2193
